# Use an official Node runtime as the base image
FROM node:14

# Set the working directory in the container to /app
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Set NPM to not require SSL
RUN npm config set strict-ssl false

# Install project dependencies
RUN npm install

# Copy the current directory contents into the container at /app
COPY . ./

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the application when the container launches
#CMD ["npm", "run", "dev"]
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
