apiVersion: v1
kind: Service
metadata:
  name: real-estate-for-all
spec:
  selector:
    app: real-estate-for-all
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort