apiVersion: v1
kind: Service
metadata:
  name: test-profe-fredy
spec:
  selector:
    app: test-profe-fredy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort